## step-1 import packages

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## step-2:create a dataframe using a list

In [3]:
names=['Ramesh','Suresh','Satish']
#pd.DataFrame(data,index,columns)
pd.DataFrame(names)

        0
0  Ramesh
1  Suresh
2  Satish

## step-3: i want to change the index

In [13]:
names=['Ramesh','Suresh','Satish']
index=['A','B','C']
#columns=['Names']
pd.DataFrame(names,index)

        0
A  Ramesh
B  Suresh
C  Satish

## step-4: Add the columns

In [11]:
names=['Ramesh','Suresh','Satish']
index=['A','B','C']
columns=['Names']
pd.DataFrame(names,index,columns)

    Names
A  Ramesh
B  Suresh
C  Satish

## step-5: Data and columns

In [10]:
names=['Ramesh','Suresh','Satish']
pd.DataFrame(names,columns=['Names'])

    Names
0  Ramesh
1  Suresh
2  Satish

In [14]:
names=['Ramesh','Suresh','Satish']
cols=['Names']
pd.DataFrame(names,columns=cols)

    Names
0  Ramesh
1  Suresh
2  Satish

## step-6: multiple Columns

In [9]:
names=['Ramesh','Suresh','Satish']
age=[20,22,24]
cols=['Names','Age']
df=pd.DataFrame(zip(names,age),columns=cols)
df

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Satish   24

## step-7: Add a new columns to already existed df

- in above first we have taken data

- then created a dataframe

- now we want to add new data based on requirement

In [10]:
city=['hyd','Pune','Blr']
#df[]#list selection
df['City']=city
df

    Names  Age  City
0  Ramesh   20   hyd
1  Suresh   22  Pune
2  Satish   24   Blr

In [11]:
marks=[80,70,90]
df['Marks']=marks
df

    Names  Age  City  Marks
0  Ramesh   20   hyd     80
1  Suresh   22  Pune     70
2  Satish   24   Blr     90

## step-8: Update the column with new values

In [12]:
df

    Names  Age  City  Marks
0  Ramesh   20   hyd     80
1  Suresh   22  Pune     70
2  Satish   24   Blr     90

In [13]:
df['Marks']

0    80
1    70
2    90
Name: Marks, dtype: int64

In [14]:
df['Marks']=[200,300,400]
df

    Names  Age  City  Marks
0  Ramesh   20   hyd    200
1  Suresh   22  Pune    300
2  Satish   24   Blr    400

## step-9: create an empty dataframe and add the columns

In [31]:
df=pd.DataFrame()

In [32]:
df

Empty DataFrame
Columns: []
Index: []

In [33]:
df['Names']=['Ramesh','Suresh','Satish']
df['Age']=[18,19,20]
df['city']=['hyd','pune','blr']
df

    Names  Age  city
0  Ramesh   18   hyd
1  Suresh   19  pune
2  Satish   20   blr

## step:10 create a Dataframe using dictionary

In [35]:
d={'Names':['Ramesh','Satish','suresh'],
   'Age':[18,19,20],
   'city':['hyd','pune','blr']
  }
pd.DataFrame(d)

    Names  Age  city
0  Ramesh   18   hyd
1  Satish   19  pune
2  suresh   20   blr

In [5]:
d={'Names':'Ramesh',
   'Age':18,
   'city':'hyd'
  }

In [6]:
pd.DataFrame(d)

ValueError: If using all scalar values, you must pass an index

In [46]:
pd.DataFrame(d,index=[0])

    Names  Age city
0  Ramesh   18  hyd

## step:11- save the dataFrame

In [51]:
# we are saving dataframe
# directory//filename.extension
# filename.ext
# .csv  or xlsx

In [48]:
df.to_csv('data.csv')

In [50]:
df.to_excel('data.xlsx')

## step:12- Read the dtaframe

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# in order to read the data
# file name.ext
# open (moboc

In [3]:
pd.read_csv('data.csv')

   Unnamed: 0   Names  Age  city
0           0  Ramesh   18   hyd
1           1  Suresh   19  pune
2           2  Satish   20   blr

In [15]:
df

    Names  Age  City  Marks
0  Ramesh   20   hyd    200
1  Suresh   22  Pune    300
2  Satish   24   Blr    400

In [16]:
pd.read_excel('data.xlsx')

   Unnamed: 0   Names  Age  city
0           0  Ramesh   18   hyd
1           1  Suresh   19  pune
2           2  Satish   20   blr

In [18]:
d={'Names':['Ramesh','Suresh','Satish'],
   'Age':[20,22,24],
   'City':['hyd','blr','pune']
  }
df=pd.DataFrame(d)
df

    Names  Age  City
0  Ramesh   20   hyd
1  Suresh   22   blr
2  Satish   24  pune

In [19]:
# new index not created
df.to_csv('data1.csv',index=False)

In [20]:
pd.read_csv('data1.csv')

    Names  Age  City
0  Ramesh   20   hyd
1  Suresh   22   blr
2  Satish   24  pune

In [22]:
df.to_excel('data1.xlsx',index=False)

In [23]:
pd.read_excel('data1.xlsx')

    Names  Age  City
0  Ramesh   20   hyd
1  Suresh   22   blr
2  Satish   24  pune

In [24]:
# when you new file save automatically new index genereted

In [28]:
# add one more column df
df['Marks']=[50,60,70]

In [29]:
df

    Names  Age  City  Marks
0  Ramesh   20   hyd     50
1  Suresh   22   blr     60
2  Satish   24  pune     70

## step:13 Drop the column

In [34]:
df.drop(['Marks'],axis=1)

    Names  Age  City
0  Ramesh   20   hyd
1  Suresh   22   blr
2  Satish   24  pune

In [35]:
df.drop(index=0)

    Names  Age  City  Marks
1  Suresh   22   blr     60
2  Satish   24  pune     70

In [36]:
df

    Names  Age  City  Marks
0  Ramesh   20   hyd     50
1  Suresh   22   blr     60
2  Satish   24  pune     70

In [40]:
df.drop(columns='Age')

    Names  City  Marks
0  Ramesh   hyd     50
1  Suresh   blr     60
2  Satish  pune     70

In [41]:
df.drop(columns=['Age','City'])

    Names  Marks
0  Ramesh     50
1  Suresh     60
2  Satish     70

In [42]:
#if i don't give argument lable
# axis=1 column
# axis=0 rows,index

In [44]:
df.drop('Marks',axis=1)

    Names  Age  City
0  Ramesh   20   hyd
1  Suresh   22   blr
2  Satish   24  pune

In [46]:
df.drop(1)        # not give axis automatically default axis=0 means rows are drop

    Names  Age  City  Marks
0  Ramesh   20   hyd     50
2  Satish   24  pune     70

**inplace**

- when we do the operation the result output is not overwriting 

- means the original dtaframe is same as it is

- in order to do this we need use **inplace**

- by default inplace=False

- make **inplace**=True if you want overwrite the result

In [47]:
df.drop('Marks',axis=1,inplace=True)

In [48]:
df

    Names  Age  City
0  Ramesh   20   hyd
1  Suresh   22   blr
2  Satish   24  pune

## step:14- Rename the column

In [53]:
d={'City':'city'}

In [62]:
df.rename({"Names":'state'},axis=1)

    state  Age  city
0  Ramesh   20   hyd
1  Suresh   22   blr
2  Satish   24  pune

In [54]:
df.rename(d)

    Names  Age  City
0  Ramesh   20   hyd
1  Suresh   22   blr
2  Satish   24  pune

In [58]:
df.rename(d,axis=1,inplace=True)

In [59]:
df

    Names  Age  city
0  Ramesh   20   hyd
1  Suresh   22   blr
2  Satish   24  pune

In [65]:
x=[1,2,3,4,5,6,7,8,9,10]
y=np.square(x)
z=np.square(y)
x,y,z

([1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100]),
 array([    1,    16,    81,   256,   625,  1296,  2401,  4096,  6561,
        10000]))

In [71]:
pd.DataFrame(zip(x,y,z),columns=['X','Y','Z'])

    X    Y     Z
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
4   5   25   125
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

In [76]:
x=list(range(1,11))
y=[i*i for i in x]
z=[i**3 for i in x]
df=pd.DataFrame(zip(x,y,z),columns=['X','Y','Z'])
df

    X    Y     Z
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
4   5   25   125
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

- len

- shape

- size

- head

- tail

- isnull

- dtypes

- info

In [77]:
len(df)

10

In [78]:
# shape
df.shape

(10, 3)

In [79]:
# size
df.size

30

In [82]:
# head
df.head()

   X   Y    Z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125

In [83]:
# tail
df.tail()

    X    Y     Z
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

In [85]:
# isnull
df.isnull()

       X      Y      Z
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
6  False  False  False
7  False  False  False
8  False  False  False
9  False  False  False

In [95]:
df.isnull().sum()

X    0
Y    0
Z    0
dtype: int64

In [87]:
# dtypes
df.dtypes

X    int64
Y    int64
Z    int64
dtype: object

In [89]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       10 non-null     int64
 1   Y       10 non-null     int64
 2   Z       10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes

## step:15 Select a column

In [97]:
df.columns

Index(['X', 'Y', 'Z'], dtype='object')

In [98]:
df['X']

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: X, dtype: int64

In [99]:
df[['X','Y']]

    X    Y
0   1    1
1   2    4
2   3    9
3   4   16
4   5   25
5   6   36
6   7   49
7   8   64
8   9   81
9  10  100

In [100]:
df[['X','Y','Z']]

    X    Y     Z
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
4   5   25   125
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

In [101]:
type(df['X'])

pandas.core.series.Series

In [102]:
df['X'].shape

(10,)

In [104]:
df[['X','Y']].shape

(10, 2)

In [106]:
df[['X','Y','Z']]

    X    Y     Z
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
4   5   25   125
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

In [107]:
df
df['X']  
df['X'].values  # extracting the dat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
df      # datfarme
df[['Y','Z']]      # selectin
df[['Y','Z']].values

array([[   1,    1],
       [   4,    8],
       [   9,   27],
       [  16,   64],
       [  25,  125],
       [  36,  216],
       [  49,  343],
       [  64,  512],
       [  81,  729],
       [ 100, 1000]])

In [111]:
df['X'].values.tolist()

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [112]:
df[['X','Y']].values.tolist()

[[1, 1],
 [2, 4],
 [3, 9],
 [4, 16],
 [5, 25],
 [6, 36],
 [7, 49],
 [8, 64],
 [9, 81],
 [10, 100]]

In [113]:
df[['X','Y','Z']].values.tolist()

[[1, 1, 1],
 [2, 4, 8],
 [3, 9, 27],
 [4, 16, 64],
 [5, 25, 125],
 [6, 36, 216],
 [7, 49, 343],
 [8, 64, 512],
 [9, 81, 729],
 [10, 100, 1000]]